# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fsmd_bd/fsmd_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fsmd_bd || ORIG_REF_NAME==fsmd_bd} -quiet] -quiet

# IP: bd/fsmd_bd/ip/fsmd_bd_processing_system7_0_0/fsmd_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fsmd_bd_processing_system7_0_0 || ORIG_REF_NAME==fsmd_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/fsmd_bd/ip/fsmd_bd_system_ila_0_0/fsmd_bd_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fsmd_bd_system_ila_0_0 || ORIG_REF_NAME==fsmd_bd_system_ila_0_0} -quiet] -quiet

# Block Designs: bd/fsmd_bd/ip/fsmd_bd_system_ila_0_0/bd_0/bd_fa77.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fa77 || ORIG_REF_NAME==bd_fa77} -quiet] -quiet

# IP: bd/fsmd_bd/ip/fsmd_bd_system_ila_0_0/bd_0/ip/ip_0/bd_fa77_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fa77_ila_lib_0 || ORIG_REF_NAME==bd_fa77_ila_lib_0} -quiet] -quiet

# IP: bd/fsmd_bd/ip/fsmd_bd_vio_0_0/fsmd_bd_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fsmd_bd_vio_0_0 || ORIG_REF_NAME==fsmd_bd_vio_0_0} -quiet] -quiet

# IP: bd/fsmd_bd/ip/fsmd_bd_fibonacci_0_0/fsmd_bd_fibonacci_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fsmd_bd_fibonacci_0_0 || ORIG_REF_NAME==fsmd_bd_fibonacci_0_0} -quiet] -quiet

# XDC: bd/fsmd_bd/ip/fsmd_bd_processing_system7_0_0/fsmd_bd_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fsmd_bd_processing_system7_0_0 || ORIG_REF_NAME==fsmd_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/fsmd_bd/ip/fsmd_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fa77_ila_lib_0 || ORIG_REF_NAME==bd_fa77_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/fsmd_bd/ip/fsmd_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fa77_ila_lib_0 || ORIG_REF_NAME==bd_fa77_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/fsmd_bd/ip/fsmd_bd_system_ila_0_0/bd_0/ip/ip_0/bd_fa77_ila_lib_0_ooc.xdc

# XDC: bd/fsmd_bd/ip/fsmd_bd_system_ila_0_0/bd_0/bd_fa77_ooc.xdc

# XDC: bd/fsmd_bd/ip/fsmd_bd_vio_0_0/fsmd_bd_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fsmd_bd_vio_0_0 || ORIG_REF_NAME==fsmd_bd_vio_0_0} -quiet] -quiet

# XDC: bd/fsmd_bd/fsmd_bd_ooc.xdc
